// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ava from "../src/ava.mjs";

var state = {
  contents: 0
};

Ava.beforeEach(function (param) {
      state.contents = state.contents + 1 | 0;
      
    });

Ava.test("[range] Should be within range 1", (function (t) {
        Ava.true_(t, state.contents > 0, "'state.contents' should be greater than 0", undefined);
        return Ava.false_(t, state.contents > 4, "'state.contents' should be less than 5", undefined);
      }));

Ava.test("[range] Should be within range 2", (function (t) {
        Ava.true_(t, state.contents > 0, "'state.contents' should be greater than 0", undefined);
        return Ava.false_(t, state.contents > 4, "'state.contents' should be less than 5", undefined);
      }));

Ava.test("[range] Should be within range 3", (function (t) {
        Ava.true_(t, state.contents > 0, "'state.contents' should be greater than 0", undefined);
        return Ava.false_(t, state.contents > 4, "'state.contents' should be less than 5", undefined);
      }));

Ava.test("[range] Should be within range 4", (function (t) {
        Ava.true_(t, state.contents > 0, "'state.contents' should be greater than 0", undefined);
        return Ava.false_(t, state.contents > 4, "'state.contents' should be less than 5", undefined);
      }));

export {
  state ,
  
}
/*  Not a pure module */
