// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ava from "../src/ava.mjs";

var state = {
  contents: 0
};

Ava.beforeEach(function (param) {
      state.contents = state.contents + 1 | 0;
      
    });

Ava.serial("Should be 1", (function (t) {
        return Ava.is(t, state.contents, 1, "'state.contents' should be 1", undefined);
      }));

Ava.serial("Should still be 1", (function (t) {
        return Ava.is(t, state.contents, 2, "'state.contents' should be 2", undefined);
      }));

export {
  state ,
  
}
/*  Not a pure module */
