// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ava from "../src/ava.mjs";

Ava.serial("[blocking] Should greet", (function (t) {
        return Ava.pass(t, "Hello world!", undefined);
      }));

Ava.serial("[blocking] Should answer question", (function (t) {
        return Ava.is(t, 42, 42, "Should be 42", undefined);
      }));

export {
  
}
/*  Not a pure module */
