// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ava from "../src/ava.mjs";

Ava.test("should run a test synchronously", (function (t) {
        return Ava.is(t, 3.14, 3.14, "Should be a tasty dessert", undefined);
      }));

export {
  
}
/*  Not a pure module */
