// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ava from "../src/ava.mjs";

Ava.skip("should skip", (function (t) {
        return Ava.fail(t, "Test is broken", undefined);
      }));

Ava.skip("should skip another", (function (t) {
        return Ava.fail(t, "Test is broken, too", undefined);
      }));

export {
  
}
/*  Not a pure module */
