// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ava from "../src/ava.mjs";
import * as $$Promise from "../helpers/promise.mjs";

function sleep(duration) {
  return $$Promise.make(function (resolve, reject) {
              setTimeout(resolve, duration);
              
            });
}

var state = {
  contents: 0
};

Ava.testAsync("[async] Should run a test asynchronously", (function (t) {
        Ava.is(t, 42, 42, "Should answer the question", undefined);
        return $$Promise.resolve(undefined);
      }));

Ava.testAsync("[async] Should run a second test at the same time", (function (t) {
        Ava.is(t, 3.14, 3.14, "Should be a tasty dessert", undefined);
        return $$Promise.resolve(undefined);
      }));

export {
  sleep ,
  state ,
  
}
/*  Not a pure module */
