// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ava from "../src/ava.mjs";
import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as Js_exn from "../node_modules/rescript/lib/es6/js_exn.js";

function $$await(prom, fn) {
  return prom.then(function (x) {
              return Promise.resolve(Curry._1(fn, x));
            });
}

Ava.test("Should throw", (function (t) {
        Ava.throws(t, (function (param) {
                return Js_exn.raiseError("SyncError");
              }), undefined, "Should throw", undefined);
        
      }));

Ava.test("Should not throw", (function (t) {
        return Ava.notThrows(t, (function (param) {
                      
                    }), "Should not throw", undefined);
      }));

Ava.testAsync("Should throw async", (function (t) {
        return Ava.throwsAsync(t, (function (param) {
                      var res = Promise.resolve(undefined);
                      return $$await(res, (function (param) {
                                    return Js_exn.raiseError("AsyncError");
                                  }));
                    }), undefined, "Should throw an 'AsyncError'", undefined);
      }));

Ava.testAsync("Should not throw async", (function (t) {
        return Ava.notThrowsAsync(t, (function (param) {
                      return Promise.resolve(undefined);
                    }), "Should not throw async", undefined);
      }));

export {
  $$await ,
  
}
/*  Not a pure module */
